Add files via upload
    articles = content_body.find_all('div', {'class': 'gs-title'})
AttributeError: 'NoneType' object has no attribute 'find_all'


printing "page_soup" from this block of code:

 for i in range(totalPages):  # page numbering starts from 0
        page_url = inputUrl + "search?q=floods#gsc.tab=0&gsc.q=floods&gsc.page=" + str(i)
        page_soup = make_soup(page_url)
        print(page_soup)

returns html that is missing tags as compared to the original website