Add files via upload
Was working previously, but errors thrown back:

 raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='selangorjournal.myhttps', port=443): Max retries exceeded with url: //selangorjournal.my/2021/05/govt-not-planning-to-enforce-nationwide-mco-proceeds-with-targeted-mco/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001B03EB0A0D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

 raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='selangorjournal.myhttps', port=443): Max retries exceeded with url: //selangorjournal.my/2021/05/govt-not-planning-to-enforce-nationwide-mco-proceeds-with-targeted-mco/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001B03EB0A0D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001B03EB0A0D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed